ProyectoLimpioCore/Models/Coche.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ProyectoLimpioCore.Models
{
    [Table("coches")]
    public class Coche
    {
        [Key]
        [Column("idcoche")]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int IdCoche { get; set; }
        [Column("marca")]
        public String Marca { get; set; }
        [Column("modelo")]
        public String Modelo { get; set; }
        [Column("conductor")]
        public String Conductor { get; set; }
        [Column("imagen")]
        public String Imagen { get; set; }
    }
}

ProyectoLimpioCore/Controllers/CochesController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoLimpioCore.Models;
using ProyectoLimpioCore.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProyectoLimpioCore.Controllers
{
    public class CochesController : Controller
    {
        IRepositoryCoches Repo;

        public CochesController(IRepositoryCoches repo)
        {
            this.Repo = repo;
        }

        public IActionResult Index()
        {
            List<Coche> coches = this.Repo.GetCoches();
            return View(coches);
        }

        [HttpPost]
        public IActionResult Index(int id)
        {
            this.Repo.EliminarCoche(id);
            List<Coche> coches = this.Repo.GetCoches();
            return View(coches);
        }

        public IActionResult Details(int id)
        {
            Coche coche = this.Repo.BuscarCoche(id);
            return View(coche);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Coche c)
        {
            this.Repo.InsertarCoche(c.Modelo, c.Marca, c.Conductor, c.Imagen);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            Coche coche = this.Repo.BuscarCoche(id);
            return View(coche);
        }

        [HttpPost]
        public IActionResult Edit(Coche coche)
        {
            this.Repo.ModificarCoche(coche);
            return RedirectToAction("Index");
        }

        public IActionResult BuscadorMarca()
        {
            return View();
        }

        [HttpPost]
        public IActionResult BuscadorMarca(String marca)
        {
            List<Coche> coches = this.Repo.BuscarMarca(marca);
            return View(coches);
        }
    }
}

ProyectoLimpioCore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProyectoLimpioCore.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

      
    }
}

ProyectoLimpioCore/Views/Coches/BuscadorMarca.cshtml
@model List<Coche>
<h1>Buscador por marca</h1>

<form method="post">
    <input type="text" name="marca" class="form-control" /><br />
    <button type="submit" class="btn btn-primary">Buscar</button>
</form>
<br />
@if (Model != null){
    <table class="table table-bordered table-success">
        <thead>
            <tr>
                <th>Marca</th>
                <th>Modelo</th>
                <th>Conductor</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Coche c in Model)
            {
                <tr>
                    <td>@c.Marca</td>
                    <td>@c.Modelo</td>
                    <td>@c.Conductor</td>
                </tr>
            }
        </tbody>
    </table>
}

ProyectoLimpioCore/Views/Coches/Create.cshtml
@model ProyectoLimpioCore.Models.Coche

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Coche</h4>
<hr />

<form method="post">
    <label>Marca</label>
    <input name="marca" class="form-control" />
    <label>Modelo</label>
    <input name="modelo" class="form-control" />
    <label>Conductor</label>
    <input name="conductor" class="form-control" />
    <label>Imagen</label>
    <input name="imagen" class="form-control" /><br />
    <input type="submit" value="Create" class="btn btn-primary" />
</form>

<a asp-action="Index" asp-controller="Coches">Back to List</a>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProyectoLimpioCore/Views/Coches/Details.cshtml
@model ProyectoLimpioCore.Models.Coche

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Coche</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdCoche)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdCoche)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Conductor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Conductor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>
        <dd class = "col-sm-10">
            <img src="@Html.DisplayFor(model => model.Imagen)" style="width: 200px; height: 200px" />
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", "Coches", new { id = Model.IdCoche }) |
    <a asp-action="Index" asp-controller="Coches">Back to List</a>
</div>

ProyectoLimpioCore/Views/Coches/Edit.cshtml
@model ProyectoLimpioCore.Models.Coche

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Coche</h4>
<hr />

<form method="post">
    <input type="text" name="idcoche" class="form-control" value="@Model.IdCoche" hidden />
    <label>Marca</label>
    <input type="text" name="marca" class="form-control" value="@Model.Marca" />
    <label>Modelo</label>
    <input type="text" name="modelo" class="form-control" value="@Model.Modelo" />
    <label>Conductor</label>
    <input type="text" name="conductor" class="form-control" value="@Model.Conductor" />
    <label>Imagen</label>
    <input type="text" name="imagen" class="form-control" value="@Model.Imagen" /><br />
    <input type="submit" value="Save" class="btn btn-primary" />
</form>

<div>
    <a asp-action="Index" asp-controller="Coches">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProyectoLimpioCore/Views/Coches/Index.cshtml
@model IEnumerable<ProyectoLimpioCore.Models.Coche>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-controller="Coches" asp-action="Create">Create New</a>
</p>
<p>
    <a asp-controller="Coches" asp-action="BuscadorMarca">Buscador por marca</a>
</p>
<table class="table table-bordered table-warning">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Modelo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Conductor)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Marca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Modelo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Conductor)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", "Coches", new { id = item.IdCoche }, new { @class = "btn btn-info" })
                @Html.ActionLink("Edit", "Edit", "Coches", new { id = item.IdCoche }, new { @class = "btn btn-warning" })
                <form class="eliminar" method="post">
                    <input type="text" name="id" value="@item.IdCoche" hidden />
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
                @*@Html.ActionLink("Delete", "Delete", "Coches", new { id = item.IdCoche }, new { @class = "btn btn-danger" })*@
            </td>
        </tr>
}
    </tbody>
</table>

@section scripts{ 
    <script>
        $(document).ready(function () {
            $(".eliminar").submit(function () {
                confirm("Seguro que desea eliminar este regristro?");
            });
        });
    </script>
    @*<script>
        $(document).ready(function () {
            $(".eliminar").click(function () {
                var res = confirm("Seguro que desea eliminar este regristro?");
                if (res == true) {
                    $(".eliminar").attr("id", $(".eliminar").attr("id"));
                } else {
                    $(".eliminar").attr("id", 0);
                }
            });
        });
    </script>*@
}

ProyectoLimpioCore/Views/Home/Index.cshtml
<h1> Index </h1>

ProyectoLimpioCore/Views/Shared/_Layout.cshtml
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Starter Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/css/starter-template.css" rel="stylesheet">
</head>

<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                </li>              
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Coches" asp-action="Index">Coches</a>
                </li>
                @*<li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                </li>
                @RenderSection("menuextra", false)
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>*@
            </ul>
            @*<form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>*@
        </div>
    </nav>

    <main role="main" class="container text-center">

        <div class="starter-template">     
            @RenderBody()
        </div>

    </main><!-- /.container -->
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="~/js/jquery-3.5.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    @RenderSection("scripts", false)
</body>
</html>